### ISSUE TITLE
Uncontrollable package break compatibility with react 15.0.0-rc.1

### ISSUE THREAD

**Issue by enten** [jquense/topeka#2]
A PR was submitted to fix compatibility with react 15.0.0-rc.1 : [uncontrollable PR #10](https://github.com/jquense/uncontrollable/pull/10).

But that fix isn't published yet on npm.

When it will be, would you be ok to upgrade uncontrallable dependency in your package.json?

**Comment by taion** [comment]
This can be closed – it's been fixed.
